---
version: '3.1'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node', 'http.host=0.0.0.0', 'transport.host=127.0.0.1', 'TZ=Asia/Taipei']
    ports: 
    - "9200:9200"
    networks: ['stack']
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports: 
    - "5601:5601"
    environment:
    - TZ=Asia/Taipei
    - SERVER_BASEPATH=/apm
    - SERVER_REWRITEBASEPATH=true    
    networks: ['stack']
    restart: unless-stopped
    depends_on: ['elasticsearch']

  apm-server:
    container_name: apm
    image: docker.elastic.co/apm/apm-server:${TAG}
    ports:
    - "8200:8200"
    - "6060:6060"
    networks: ['stack']
    restart: unless-stopped
    environment: ['TZ=Asia/Taipei']
    depends_on: ['elasticsearch']
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.rum.event_rate.limit=1000
        -E apm-server.kibana.path=/apm
networks: {stack: {}}
